# -----------------------------
# Database Configuration
# -----------------------------

db.driver=org.h2.Driver
db.url=jdbc:h2:mem:quantitydb
db.username=naman
db.password=

# -----------------------------
# Connection Pool Configuration
# -----------------------------

connection.pool.size=5
connection.pool.timeout=3000

# -----------------------------
# Repository Configuration
# -----------------------------

repository.type=database

# options:
# repository.type=cache
# repository.type=database


# -----------------------------
# Logging Configuration
# -----------------------------

logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG